---
version: '3'
services:
  postgresql:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ../.data-auth-api-full/postgresql:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
